
#PRIORITIZATION=$FAQAS/PARAM_GSL/PRIORITIZATION
#PRIORITIZATION=$FAQAS/GSL/PRIORITIZATION
PRIORITIZATION=$FAQAS/CSP_GSL/PRIORITIZATION

#ORIGINAL_COV=$FAQAS/PARAM_GSL/COVERAGE_TESTS_MATCH
#ORIGINAL_COV=$FAQAS/GSL/COVERAGE_TESTS_MATCH
ORIGINAL_COV=$FAQAS/CSP_GSL/COVERAGE_TESTS_MATCH

#WORKING=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASTce/process/LIBUTIL
#WORKING=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASTce/process/CSP_GSL
#WORKING=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASTce/process/PARAM_GSL

#WORKING=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASTce/process/SDL/LIBUTIL
WORKING=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASTce/process/SDL/CSP_GSL
#WORKING=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASTce/process/SDL/PARAM_GSL

ALL_TRACES=$WORKING/all_traces_filtered.csv
ORIGINAL_ORDER=$WORKING/test_cases

PROCESS=$FAQAS/srcirorfaqas/FAQASOptimizations/FAQASPrioritization/PROCESS_ONLY_COVERED/process_time.py

#python3.6 $PROCESS $ALL_TRACES $PRIORITIZATION $ORIGINAL_ORDER "/home/gsl/libutil/tst/" $ORIGINAL_COV
python3.6 $PROCESS $ALL_TRACES $PRIORITIZATION $ORIGINAL_ORDER "/home/csp/libparam/lib/libgscsp/tst/" $ORIGINAL_COV
#python3.6 $PROCESS $ALL_TRACES $PRIORITIZATION $ORIGINAL_ORDER "/home/csp/libparam/tst/" $ORIGINAL_COV

